export const STRINGS = {
    common: {
        loading: 'Loading...',
        error: 'Error',
        success: 'Success',
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        edit: 'Edit',
        back: 'Back',
        close: 'Close',
        description: 'Description',
        amount: 'Amount',
        date: 'Date',
    },
    recurring: {
        title: 'Recurring',
        newTemplate: 'New Template',
        deleteConfirmTitle: 'Delete',
        deleteConfirmMessage: 'Are you sure you want to delete this recurring transaction?',
        deleteAction: 'Delete',
        cancelAction: 'Cancel',
        frequency: 'FREQUENCY',
        activateTemplate: 'Activate Template',
        emptyTitle: 'No recurring transactions set up.',
        emptySubtitle: 'Automate your monthly salaries, rent, or bills.',
        frequencies: {
            daily: 'DAILY',
            weekly: 'WEEKLY',
            monthly: 'MONTHLY',
        },
        placeholders: {
            description: 'e.g. Monthly Rent',
            amount: '0.00',
        }
    },
    reports: {
        title: 'Reports',
        monthSelector: 'MMMM yyyy',
        aiInsightTitle: 'AI-POWERED INSIGHT',
        aiRefreshing: '(REFRESHING...)',
        totalSpending: 'TOTAL SPENDING',
        totalIncome: 'TOTAL INCOME',
        financialTrend: 'Financial Trend',
        historyAnalysis: 'HISTORY ANALYSIS',
        budgetTracking: 'Budget Tracking',
        noBudgets: 'No budgets set for this month.',
        aiError: 'Unable to generate insights at this time.',
    },
    login: {
        brandName: 'Household',
        brandTagline: 'Ledger Management System',
        terms: 'Terms of Service',
        privacy: 'Privacy Policy',
        googleLoginError: 'Google Login Error',
        appleLoginError: 'Apple Login Error',
        missingInfo: 'Missing Info',
        fillAllFields: 'Please fill in all fields.',
        enterName: 'Please enter your name.',
        accountCreated: 'Account created! Please check your email.',
        tooManyAttempts: 'Too Many Attempts',
        accountLocked: 'Account locked for 30 seconds.',
        selectStaff: 'Select Staff',
        selectResident: 'Select Resident',
        loginAs: 'Login as',
    },
    auth: {
        email: 'Email',
        social: 'Social',
        fullName: 'Full Name',
        fullNamePlaceholder: 'Enter your name',
        emailAddress: 'Email Address',
        emailPlaceholder: 'name@example.com',
        password: 'Password',
        passwordPlaceholder: 'Enter password',
        createAccount: 'Create Account',
        signIn: 'Sign In',
        alreadyHaveAccount: 'Already have an account? ',
        dontHaveAccount: "Don't have an account? ",
        signUp: 'Sign Up',
        hidePassword: 'Hide password',
        showPassword: 'Show password',
        togglePasswordHint: 'Toggles password visibility',
    }
};
